emmo-repo/EMMO

emmo/core/emmo-core.owl, emmo/emmo.owl
Added annotations to some relations
=> Added annotations to more relations

catalog-v001.xml, emmo-all.owl, emmo/catalog-v001.xml, emmo/core/catalog-v001.xml, emmo/core/emmo-4d.owl, emmo/core/emmo-annotations.owl, emmo/core/emmo-mereotopology.owl, emmo/core/emmo-physical.owl, emmo/emmo.owl, emmo/perspectives/catalog-v001.xml, emmo/perspectives/emmo-existent.owl, emmo/perspectives/emmo-impression.owl, emmo/perspectives/emmo-processual.owl, emmo/perspectives/emmo-semiotics.owl, graphical/catalog-v001.xml, graphical/emmo-graphical.owl, material/catalog-v001.xml, material/emmo-material.owl, math/catalog-v001.xml, math/emmo-geometry.owl, math/emmo-math.owl, models/catalog-v001.xml, models/emmo-models.owl, properties/catalog-v001.xml, properties/emmo-physical-properties.owl, properties/emmo-properties.owl, usercase/catalog-v001.xml, usercase/emmo-usercase.owl
The EMMO is now accessible remotely via http://emmo.info/emmo/emmo.owl
=> Redirecting

README.md, doc/installing_factplusplus.md
Added a short instruction on how to install the FaCT++ plugin on Windows - since it is an essential tool to have when working with EMMO.
=> Installing factplusplus plugin

middle/units.owl
=> Updated hasUnit relations, added viscosity and removed dublicated DegreeCelcius

middle/materials.owl
These relations are inherited from Nucleon
=> Removed hasSpatialDirectPart some Quark relations from Neutron and Proton

middle/metrology.owl, middle/siunits.owl
Changed dimensionality restrictions on units from existential to universal.
Also added dimension restriction to UnitOne as well as a single cardinality restriction on all measurement units:
MeasurementUnit hasPhysicsDimension exactly 1 PhysicsDimension
=> Universal dimensions

middle/isq.owl, middle/metrology.owl, middle/siunits.owl, middle/units-extension.owl, top/annotations.owl
Adding a first draft of units-extension.
Changes to other owl files:
middle/siunits.owl: Explicitely subclassed SIExactConstant + added some annotations
middle/isq.owl: Saved with Protege 4.5.9.2019
top/annotations.owl: Added seeAlso sub-annotation IECEntry to refer to ISO 80000 definition at IEC.
=> Units extension

middle/isq.owl, middle/metrology.owl, middle/siunits.owl
Added annotations to SIUnit and MultipleUnit and SubMultipleunit.
=> Added annotations

README.md
Added MarketPlace, VIMMP and OntoTrans to acknowledgement
This replaces PR #78  with correct target branch
=> Issue #71: project support axknowledgements

README.md
Updated the description of the perceptual perspective.
This replaces PR #77, because of wrong target branch
=> Issue72 improvements in readme

emmo-inferred.owl, top/mereotopology.owl, top/physical.owl
Item was declared under physical module.
=> IMPORTANT Top Level Issue

middle/isq.owl, middle/metrology.owl, middle/units-extension.owl, top/annotations.owl
Added range to annotation properties.
Also added qudtEntry annotations to physical quantities + other cleanup of annotations.
=> Annotation range

.github/scripts/makeindex.sh, .github/scripts/update_pages.sh, .github/workflows/ci_emmocheck.yml
Fixed update_pages and ci_emmocheck
- added increased verbosity to generation of index.html
- fixed false failure if github pages is up-to-date
- added missing emmo.owl argument to emmocheck
=> Fixing CI scripts

middle/isq.ttl, middle/math.ttl
Implemented arrays.  Replaces PR #130
=> Implement arrays

middle/metrology.ttl, middle/properties.ttl, top/annotations.ttl
Added uncertainty. Based on VIM and implemented according to the figure below:
=> Uncertainty

.github/scripts/makeversions.sh, doc/emmodoc/mkfigs.py, middle/isq.ttl, middle/manufacturing.ttl
Added workaround in formatting bugs in inferred ontology.
=> Cleanup scripts

doc/emmodoc/emmodoc-meta.yaml, doc/emmodoc/introduction.md, doc/emmodoc/relations.md
Dear EMMOntologists,
I was reading the documentation and fixed a few typos. I hope this helps :)
Otello
=> Fixed typos in the documentation.

disciplines/materials.ttl
Changed elucidation of ReactiveMaterial to 
A material that takes active part in a chemical reaction.
This way ReactiveMaterial also include catalysts.
=> Changed elucidation of ReactiveMaterial

disciplines/manufacturing.ttl, disciplines/metrology.ttl, disciplines/models.ttl
Replaced hasParticipant relations with hasTemporaryParticipant where it made sense (which were everywhere).
Also import workflows.ttl in manufacturing.ttl
=> Replaced old hasParticipant relations with hasTemporaryParticipant

perspectives/semiotics.ttl
=> Normalised turtle format for semiotics.ttl

multiperspective/symbolic.ttl
=> Update abstract and other metadata of the symbolic module

perspectives/semiotics.ttl
Added missing elucidations to the semiotics module. 
Also added hasDescription relation.
=> Added missing elucidations to the semiotics module

.github/ABOUT.md, .github/expected_redirections.yaml, .github/pages-index.html.in, .github/scripts/makeindex.sh, .github/scripts/makeversions.sh, .github/versions.txt, .github/workflows/ci_emmocheck.yml, .github/workflows/ci_redirectioncheck.yml, .github/workflows/update_pages.yml, doc/emmodoc/classes.md
Fixed issues with the GitHub workflows, including:
- Updated GitHub Actions to the latest versions and use Python 3.11.
- Use turtle as the base file format to fix issues with rdfxml not supporting IRIs starting with a letter.
- Fixed issues with the documentation generation 
- Added a new CI workflow for testing redirections (TODO: uncomment failing tests and fix the redirections on w3id)
=> Fix GitHub workflow

perspectives/standardmodel.ttl
Corrected IRI for MultiParticlePath: 5e00b1db_48fc_445b_82e8_ab0e2255bf52 -> EMMO_5e00b1db_48fc_445b_82e8_ab0e2255bf52.
=> Fixed IRI of MultiParticlePath

disciplines/chemistry.ttl
ChemicalCompositionQuantity is already defined in isq.
=> Remove ChemicalCompositionQuantity from chemistry
